name: Build and push Docker Image to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/docker-build-push-action
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: khadijaelm24/face_recognition
        tags: latest # keeping simply a single tag for a docker image's push
        registry: docker.io # same registry's name 
        dockerfile: Dockerfile # references to the written Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}